# Generated by Django 6.0 on 2025-12-24 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0005_alter_patient_id'),
        ('specialist', '0013_alter_specialistappeal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'أقل من المتوسط'), (2, 'متوسط'), (3, 'جيد'), (4, 'جيد جدًا'), (5, 'ممتاز')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_ratings', to='patient.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='specialist.specialist')),
            ],
            options={
                'unique_together': {('patient', 'specialist')},
            },
        ),
    ]
