# Generated by Django 5.2.9 on 2025-12-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_alter_patient_id'),
        ('specialist', '0005_alter_specialist_id_alter_specialistcertificate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('room_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('meeting_url', models.URLField(editable=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'قادمة'), ('COMPLETED', 'منتهية'), ('CANCELED', 'ملغاة')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patient.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='specialist.specialist')),
            ],
        ),
    ]
