# Generated by Django 6.0 on 2025-12-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='patient_response_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='patient_suggested_times',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'بانتظار موافقة المريض'), ('CONFIRMED', 'مؤكدة'), ('REJECTED', 'مرفوضة'), ('COMPLETED', 'منتهية'), ('CANCELED', 'ملغاة')], default='PROPOSED', max_length=20),
        ),
    ]
