# Generated by Django 6.0 on 2025-12-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_session_patient_response_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('INITIAL', 'جلسة أولى'), ('TREATMENT', 'جلسة علاجية')], default='TREATMENT', max_length=20),
        ),
    ]
