# Generated by Django 6.0 on 2025-12-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='specialist_joined',
            field=models.BooleanField(default=False),
        ),
    ]
