# Generated by Django 6.0 on 2025-12-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_session_specialist_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
