# Generated by Django 6.0 on 2025-12-23 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_session_meeting_url'),
        ('specialist', '0013_alter_specialistappeal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='session.session')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist')),
            ],
        ),
    ]
