# Generated by Django 6.0 on 2025-12-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_sessionnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionnote',
            name='duration_seconds',
        ),
    ]
