# Generated by Django 5.2.9 on 2025-12-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_session_id'),
        ('session', '0008_remove_sessionnote_duration_seconds'),
    ]

    operations = [
    ]
