# Generated by Django 6.0 on 2025-12-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_merge_20251224_1125'),
        ('session', '0010_alter_session_id'),
    ]

    operations = [
    ]
