# Generated by Django 6.0 on 2025-12-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_merge_20251224_1124'),
        ('session', '0011_merge_0009_merge_20251224_1125_0010_alter_session_id'),
    ]

    operations = [
    ]
