# Generated by Django 6.0 on 2025-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_merge_20251224_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
