# Generated by Django 6.0 on 2025-12-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_session_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='reminder_sent',
        ),
    ]
