# Generated by Django 5.2.16 on 2026-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_remove_session_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
