# Generated by Django 6.0 on 2025-12-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('patient', '0003_remove_patient_child_name_patient_file_number_and_more'),
        ('specialist', '0004_remove_specialist_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='audio_files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='specialist.specialist'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20),
        ),
    ]
