# Generated by Django 5.2.9 on 2025-12-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_audio_files_assessment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
