# Generated by Django 6.0 on 2025-12-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_audio_files_assessment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('SPECIALIST_BUSY', 'لدى الأخصائي عدد من الحالات الحالية ولا يمكنه إضافة حالة جديدة في الوقت الحالي، اختر أخصائي آخر'), ('NEEDS_INPERSON', 'الحالة تحتاج تقييم حضوري مباشر'), ('NOT_REQUIRED', 'الحالة لا تحتاج تدخل أخصائي تخاطب في الوقت الحالي')], max_length=120, null=True),
        ),
    ]
