# Generated by Django 6.0 on 2025-12-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessment_id'),
        ('assessment', '0003_assessment_rejection_reason'),
    ]

    operations = [
    ]
