# Generated by Django 6.0 on 2025-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('SPECIALIST', 'Specialist')], max_length=20, null=True),
        ),
    ]
