# Generated by Django 5.2.9 on 2025-12-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_alter_patient_id'),
        ('specialist', '0007_alter_specialistappeal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشطة'), ('COMPLETED', 'مكتملة'), ('CANCELED', 'ملغاة')], default='DRAFT', max_length=20)),
                ('problem_description', models.TextField()),
                ('long_term_goal', models.TextField()),
                ('sessions_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('session_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patient.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='specialist.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('target_accuracy', models.PositiveIntegerField(help_text='Percentage like 80')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_term_goals', to='treatment.treatmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('accuracy', models.PositiveIntegerField(blank=True, null=True)),
                ('specialist_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='treatment.treatmentplan')),
            ],
        ),
    ]
