# Generated by Django 6.0 on 2025-12-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_alter_progressreport_id_alter_shorttermgoal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_name', models.CharField(max_length=20)),
                ('goal_of_day', models.TextField(blank=True)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='treatment.treatmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('COMPLETED', 'تمت'), ('NOT_COMPLETED', 'لم تتم')], max_length=20, null=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='treatment.dailyplan')),
            ],
        ),
    ]
