# Generated by Django 6.0 on 2025-12-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_dailyplan_dailytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='long_term_goal',
            field=models.TextField(blank=True),
        ),
    ]
