# Generated by Django 6.0 on 2025-12-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_alter_treatmentplan_long_term_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='long_term_goal',
        ),
    ]
