# Generated by Django 6.0 on 2025-12-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_remove_treatmentplan_long_term_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='target_letter',
            field=models.CharField(default='a', help_text='الحرف المستهدف في المهمة', max_length=1),
            preserve_default=False,
        ),
    ]
