# Generated by Django 6.0 on 2025-12-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_dailytask_target_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='execution_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
