# Generated by Django 6.0 on 2025-12-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0007_dailytask_completed_at_dailytask_execution_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='specialist_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الأخصائي'),
        ),
    ]
