# Generated by Django 5.2.9 on 2025-12-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_alter_dailyplan_id_alter_dailytask_id_and_more'),
        ('treatment', '0008_dailytask_specialist_notes'),
    ]

    operations = [
    ]
