# Generated by Django 6.0 on 2025-12-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_merge_20251224_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shorttermgoal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'بانتظار الدفع'), ('ACTIVE', 'نشطة'), ('COMPLETED', 'مكتملة'), ('CANCELED', 'ملغاة')], default='DRAFT', max_length=20),
        ),
    ]
