# Generated by Django 6.0 on 2025-12-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_merge_20251224_1124'),
        ('treatment', '0010_alter_dailyplan_id_alter_dailytask_id_and_more'),
    ]

    operations = [
    ]
