# Generated by Django 5.2.16 on 2026-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0011_merge_20251224_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='target_letter',
            field=models.CharField(help_text='الحرف المستهدف في المهمة', max_length=5),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shorttermgoal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
