# Generated by Django 6.0 on 2025-12-23 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_id'),
        ('treatment', '0005_remove_treatmentplan_long_term_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='treatment.treatmentplan'),
        ),
    ]
