# Generated by Django 6.0 on 2025-12-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_id'),
        ('payment', '0004_payment_treatment_plan'),
    ]

    operations = [
    ]
