# Generated by Django 6.0 on 2025-12-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_merge_20251224_1124'),
        ('payment', '0006_alter_payment_id'),
    ]

    operations = [
    ]
