# Generated by Django 6.0 on 2025-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20),
        ),
    ]
