# Generated by Django 6.0 on 2025-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_specialist_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
