# Generated by Django 6.0 on 2025-12-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0003_specialist_certificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='certificate_file',
        ),
        migrations.CreateModel(
            name='SpecialistCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='specialist.specialist')),
            ],
        ),
    ]
