# Generated by Django 6.0 on 2025-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0004_remove_specialist_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
