# Generated by Django 6.0 on 2025-12-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_alter_specialist_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('APPEALED', 'تم الاعتراض')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SpecialistAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='specialist.specialist')),
            ],
        ),
    ]
