# Generated by Django 5.2.9 on 2025-12-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_alter_specialist_id_alter_specialistcertificate_id'),
        ('specialist', '0005_alter_specialist_years_of_experience'),
    ]

    operations = [
    ]
