# Generated by Django 5.2.9 on 2025-12-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0006_merge_20251220_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistappeal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
