# Generated by Django 6.0 on 2025-12-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_alter_specialist_id_alter_specialistcertificate_id'),
        ('specialist', '0006_alter_specialist_verification_status_and_more'),
    ]

    operations = [
    ]
