# Generated by Django 6.0 on 2025-12-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0007_merge_20251220_1915'),
        ('specialist', '0007_merge_20251220_1937'),
    ]

    operations = [
    ]
