# Generated by Django 6.0 on 2025-12-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0008_merge_20251220_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialistcertificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
