# Generated by Django 6.0 on 2025-12-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0006_merge_20251220_1449'),
        ('specialist', '0008_merge_20251220_2008'),
    ]

    operations = [
    ]
