# Generated by Django 5.2.9 on 2025-12-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0007_alter_specialistappeal_id'),
        ('specialist', '0008_merge_20251220_2008'),
    ]

    operations = [
    ]
