# Generated by Django 6.0 on 2025-12-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0006_merge_20251220_1449'),
        ('specialist', '0009_alter_specialist_id_alter_specialistcertificate_id'),
    ]

    operations = [
    ]
