# Generated by Django 6.0 on 2025-12-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0009_merge_20251221_2131'),
        ('specialist', '0010_merge_20251221_2200'),
    ]

    operations = [
    ]
