# Generated by Django 5.2.9 on 2025-12-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0009_merge_20251221_2049'),
        ('specialist', '0011_merge_20251222_0821'),
    ]

    operations = [
    ]
