# Generated by Django 6.0 on 2025-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0012_merge_20251222_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistappeal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
