# Generated by Django 6.0 on 2025-12-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0014_alter_specialist_id_alter_specialistappeal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='bio',
            field=models.TextField(blank=True, verbose_name='نبذة عن الأخصائي'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialistappeal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialistcertificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
